import { DecisionBoardPick, NormalizedApexGame } from '../types.js';
import { parlayService, selectEventRepresentatives, selectParlaySlateRows, selectStraightAlternatives } from './parlayService.js';
function pick(id:string,event:string,sport:'MLB'|'NFL',bookOffers:any[],extra:Partial<DecisionBoardPick>={}):DecisionBoardPick{return {rank:0,eventId:event,eventTitle:event,sport,league:sport,startTime:'2099-01-01T00:00:00Z',pickType:'PLAYER_PROP',displayPick:id,selectionLabel:id,gameMarketType:null,playerName:id,playerId:id,marketKey:'test',marketCategory:'Test',side:'OVER',line:1.5,sportsbook:bookOffers[0]?.sportsbook||'Book',oddsAmerican:bookOffers[0]?.oddsAmerican||-110,apexProbability:.55,breakEvenProbability:.524,edgePercentagePoints:2.6,expectedValuePercent:5.0,reliabilityTier:'STRONG',modelVersion:'TEST',modelValidationStatus:'PROSPECTIVE_VALIDATED',calibrationStatus:null,quoteTimestamp:new Date().toISOString(),quoteAgeSeconds:5,pointInTimeValid:true,v3ShadowProbability:null,v3ShadowSupportsProduction:null,rationale:[],source:'LIVE_EVALUATION',bookOffers,...extra};}
function game(id:string,sport:'MLB'|'NFL',start:string):NormalizedApexGame{return {eventId:id,sport,status:'UPCOMING',startTime:start,homeTeam:`${id} H`,awayTeam:`${id} A`,league:sport} as any;}
export function runParlayVerificationSuite(){
 const tests:any[]=[];const t=(name:string,fn:()=>boolean)=>{let ok=false,detail='';try{ok=fn();detail=ok?'PASS':'assertion false';}catch(e:any){detail=e.message;}tests.push({testName:name,status:ok?'PASS':'FAIL',details:detail});};
 const a=pick('A','E1','MLB',[{sportsbook:'DraftKings',oddsAmerican:-110,quoteTimestamp:new Date().toISOString()},{sportsbook:'FanDuel',oddsAmerican:-105,quoteTimestamp:new Date().toISOString()}]);
 const b=pick('B','E2','NFL',[{sportsbook:'DraftKings',oddsAmerican:+100,quoteTimestamp:new Date().toISOString()}]);
 t('Common sportsbook is required and selected',()=>parlayService.buildTickets([a,b],2,{}).tickets[0]?.sportsbook==='DraftKings');
 t('Same-event combination is blocked',()=>parlayService.buildTickets([a,{...b,eventId:'E1'}],2,{}).tickets.length===0);
 t('No common sportsbook yields no ticket',()=>parlayService.buildTickets([a,pick('C','E3','NFL',[{sportsbook:'Caesars',oddsAmerican:-110,quoteTimestamp:new Date().toISOString()}])],2,{}).tickets.length===0);
 t('Combined decimal and American odds are coherent',()=>{const x=parlayService.buildTickets([a,b],2,{}).tickets[0];return !!x&&x.combinedDecimalOdds>3.7&&x.combinedAmericanOdds>270;});
 t('Independence probability is product of leg probabilities',()=>{const x=parlayService.buildTickets([a,b],2,{}).tickets[0];return !!x&&Math.abs(x.independenceProbability-.55*.55)<1e-9;});
 const early={...b,pickType:'GAME_MARKET' as const,gameIntegrityStatus:'QUALIFIED' as const,modelValidationStatus:'EARLY_EVIDENCE' as const};
 t('Early game-model leg caps ticket stake at 0.25u',()=>{const all=[...parlayService.buildTickets([a,early],2,{}).tickets,...parlayService.buildTickets([a,early],2,{}).reviewTickets];return !!all[0]&&all[0].suggestedStakeUnits<=.25;});
 t('Extreme combined EV is REVIEW, not auto-qualified',()=>{const x=pick('X','E4','MLB',[{sportsbook:'DraftKings',oddsAmerican:+150,quoteTimestamp:new Date().toISOString()}],{apexProbability:.75});const y=pick('Y','E5','NFL',[{sportsbook:'DraftKings',oddsAmerican:+150,quoteTimestamp:new Date().toISOString()}],{apexProbability:.75});return parlayService.buildTickets([x,y],2,{}).tickets.length===0&&parlayService.buildTickets([x,y],2,{}).reviewTickets.length===1;});
 t('Primary pool keeps only the strongest leg per event',()=>{const reps=selectEventRepresentatives([a,{...a,displayPick:'A2',selectionLabel:'A2',expectedValuePercent:2,apexProbability:.53},b]);return reps.length===2&&new Set(reps.map(x=>x.eventId)).size===2&&reps.some(x=>x.displayPick==='A');});
 t('Straight alternatives are distinct-event recommendations',()=>{const rows=selectStraightAlternatives([a,{...a,displayPick:'A2',selectionLabel:'A2'},b,pick('C','E3','MLB',[{sportsbook:'DraftKings',oddsAmerican:-105,quoteTimestamp:new Date().toISOString()}])],3);return rows.length===3&&new Set(rows.map(x=>x.eventId)).size===3;});
 t('ALL SPORTS slate round-robins sports before repeating',()=>{const base=Date.UTC(2099,0,1);const rows=selectParlaySlateRows([game('M1','MLB',new Date(base+1000).toISOString()),game('M2','MLB',new Date(base+2000).toISOString()),game('M3','MLB',new Date(base+3000).toISOString()),game('N1','NFL',new Date(base+4000).toISOString()),game('N2','NFL',new Date(base+5000).toISOString())],'ALL',4,base);return rows.length===4&&rows[0].sport==='MLB'&&rows[1].sport==='NFL'&&rows[2].sport==='MLB'&&rows[3].sport==='NFL';});
 t('Parlay funnel counts common-book and value-cleared combinations',()=>{const r=parlayService.buildTickets([a,b],2,{});return r.metrics.combinationsConsidered===1&&r.metrics.distinctEventCombinations===1&&r.metrics.commonBookCombinations===1&&r.metrics.valueClearedCombinations===1;});
 return {allPassed:tests.every(x=>x.status==='PASS'),verificationTimestamp:new Date().toISOString(),engineVersion:'APEX_PARLAY_V1_13_1',keyedOddsRequestsConsumed:0,tests};
}
